# Generated by Django 3.2.4 on 2021-11-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeScreen', '0002_auto_20211125_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadresume',
            name='job_des_degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uploadresume',
            name='job_des_skills',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
